### ISSUE TITLE
[Suggestion] - Configurable noteblock 'ding' sound distance.

### ISSUE THREAD

**Issue by mibby** [graywolf336/CasinoSlots#59]
@graywolf336 

Would it be possible to configure the noteblock 'ding' sounds that come from the slot machines? Such as the distance? I have users complaining that they hear the slot dings from over 100 blocks away.

**Comment by Crezarius** [comment]
I completely agree. I love this mod and so do my users but Im about to uninstall it for the same complaint. My small server means almost everybody hears it. I want to remove the noise all together or at least go back to the sound centered on the player. 

Im going to go give version 2.5.6 a go and hope it works well since the next patch changed it to "Play a sound at location and not just for the playing player"

**Comment by graywolf336** [comment]
Change the Bukkit version to negative and they will all go away. I've been
wanting to change it up for a while to make it configurable per type of
slot machine.

**Comment by mibby** [comment]
The bukkit version in the CasinoSlot's config.yml? I don't want to disable all sounds permanently, just reduce the radius in which they play at to ~5-10 blocks from the actual slot machine. But I suppose disabling all sounds will do as a temporary resolution to the global sounds issue.

**Comment by graywolf336** [comment]
Right, that's the best possible for now. I will work on it this weekend so that the radius is configurable and the sound it makes is configurable, might even make sounds configurable when an action is won.

**Comment by graywolf336** [comment]
Someone mind testing the newest version? I turned down items to try and get the ding distance to not be the entire server....can't test it at the moment though. https://ci2.craftyn.com/job/CasinoSlots/

**Comment by mibby** [comment]
@graywolf336 Still hear it from extreme distances. :(

**Comment by graywolf336** [comment]
@mibby Mind trying the change I just pushed? I haven't tested it nor do I know what it sounds like, but just to see if that fixes it.

**Comment by mibby** [comment]
@graywolf336 It did not fix the issue and I think it broke something. Playing the slot machine up close, the noteblock plays two sounds at once every spin, while the third spin has an off pitch note. Far away, I still hear the noteblocks as if I'm at the slot, except I only hear one note every spin instead of two.

**Comment by graywolf336** [comment]
@mibby ohhhhh, I forgot it plays more than just the final sound. Okay, give me a few minutes and I'll find the other ones and make a change. I'll tag you again to try the newest build.

**Comment by graywolf336** [comment]
@mibby mind verifying it is fixed? I finally got a small test server setup where I could test it, but want second ears to verify it is fixed.

**Comment by mibby** [comment]
@graywolf336 Sure. I'll update and get back to you in a half hour.

**Comment by graywolf336** [comment]
@mibby thanks

**Comment by mibby** [comment]
My apologies for getting back to you so late. 

Confirmed fixed now. :) No double notes, no distance sounds. The only minor complaint I have is the 4th note (the final high pitched ding to indicate the slot is finished) plays a bit abruptly. Could use another second of pause in my opinion.
